### ISSUE TITLE
A change of how island chat works

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Chat#11]
#### Is your feature request related to a problem?
Yes, at the moment, if someone toggles island chat ON, it is toggled for all players on it, which makes no sense, which means - the player that toggled it has forced others to write their messages in Island Chat as well. It should be player-sensitive. To be more exact, each island chat user should be binded to island, but it's up to them to decide whether they want to write in it or not. 

#### Describe the solution you'd like us to implement.
The island chat messages should be sent to all players on island and there should not exist an option to toggle it's messages on or off. If the player does not wish to read those messages, he can always leave the island, or if some1 doesn't want others to read their island chat, they can expel that player or lock the island.

It should work similiar to team chat, it's messages are popping no matter whether you toggled your own team chat or not. The toggle command only decides whether future messages will be redirected into the teamchat automatically or public.

**Comment by wellnesscookie** [comment]
I will be more than glad to submit a PR of my recoded version of Chat addon that works as above, if you  decide to agree on this with me.

**Comment by tastybento** [comment]
Yes, I agree. Please submit the PR and I'll review.
