### ISSUE TITLE
Banned are being sent teamchat messages

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Chat#12]
#### Describe the bug
In #TeamChat method, the #getMembers followed by #getkeySet returns members of the island, as well as banned players on it. This is leading to teamchat messages being sent to banned users as well which should not.

#### Steps to reproduce the behavior
1. Have a team
2. Ban a user
3. Send message to team chat
4. Look at banned user's chat

#### Expected behavior
Not return banned users as members or just filter them better in the #teamChat method. I think it is up to BBox to fix this.

##### BentoBox Version (Mandatory)

```
BentoBox 1.9.2 - 1.13.2
Chat (latest and recoded by myself to ignore banned)
```

**Comment by BONNe** [comment]
The line that is incorrect:
https://github.com/BentoBoxWorld/Chat/blame/develop/src/main/java/world/bentobox/chat/listeners/ChatListener.java#L91
