### ISSUE TITLE
Coop player can see Team Chat

### ISSUE THREAD

**Issue by kleinesNugget** [BentoBoxWorld/Chat#20]
#### Describe the bug

A cooped player can read the Team Chat of the island they're cooped on, while not even being able to write in the team chat themselves, because they're technically not in the island team and it would interfere with their own island team chat.

#### Steps to reproduce the behavior

1. Coop a player
2. Write in Team Chat
3. Cooped player can read the Team Chat

#### Expected behavior

The cooped player is not supposed to be able to read the Team Chat
(Or might make it an island setting on who is supposed to be able to read and send messages to it, or just simply a config thing)

##### Output of `/bbox version` (Mandatory)

```
Running PAPER 1.16.1.
BentoBox version: 1.14.2
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Loaded Addons:
AdvancedIslandFly 1.0-SNAPSHOT (ENABLED)
Border 1.0.9-SNAPSHOT-LOCAL (ENABLED)
BSkyBlock 1.14.0 (ENABLED)
Chat 1.0.4 (ENABLED)
Level 2.4.0-SNAPSHOT-LOCAL (ENABLED)
Likes 2.0.0-SNAPSHOT-LOCAL (ENABLED)
Limits 1.14.0 (ENABLED)
Warps 1.9.0 (ENABLED)
```

**Comment by tastybento** [comment]
I made team chat just for MEMBER and above because of this conflict. Please try the latest snapshot and confirm.
