### ISSUE TITLE
Chat placeholders parse for each player

### ISSUE THREAD

**Issue by fredthedoggy** [BentoBoxWorld/Chat#22]
#### Describe the bug

I was playing with some friends on a 20+ player oneblock island, when I tested /is teamchat. I sent a message and it seemed to work, but every player saw their own name instead of mine
#### Steps to reproduce the behavior

Using Bentobox 1.15.1 configure chat to work with aoneblock.
Then get 2 accounts online on the same island, and say a message in teamchat.
#### Expected behavior

It should show the user who sent the message on all screens
##### Output of `/bbox version` (Mandatory)

```
Running PAPER 1.16.3.
BentoBox version: 1.15.1
Database: JSON
Loaded Game Worlds:
oneblock_world (OneBlock): Overworld, Nether, The End
Loaded Addons:
AOneBlock 1.4.0 (ENABLED)
Border 2.0.1-SNAPSHOT-b65 (ENABLED)
Challenges 0.8.0 (ENABLED)
Chat 1.0.4 (ENABLED)
ControlPanel 1.12.0-SNAPSHOT-b11 (ENABLED)
Level 1.9.3 (ENABLED)
Likes 1.7.0 (ENABLED)
MagicCobblestoneGenerator 2.0.0-GamersNest-LOCAL (ENABLED)
Upgrades 0.2.0-SNAPSHOT-b64 (ENABLED)
Visit 1.0.0-SNAPSHOT (ENABLED)
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

I was OPed with all the permissions on luckperms

**Comment by tastybento** [comment]
Hmm, I can't seem to replicate that right now with the latest version. Please try Version 1.1.1.

**Comment by fredthedoggy** [comment]
Still Happening. I had 3 players online (from the team) and 16 people online in total.
I am on 1.1.1

**Comment by tastybento** [comment]
Screenshots please.

**Comment by fredthedoggy** [comment]
Totally Forgot This Existed- Sorry

Heres a Video Demonstrating it, where I am logged in onto Both accounts. Seems to only effect TeamChat though, not regular Island chat.
https://user-images.githubusercontent.com/45927799/108286542-447bf580-7157-11eb-8ca6-0550bc8c195b.mp4

**Comment by tastybento** [comment]
Please explain more! I don't understand your Edit above. As the chat syntax is a variable, share what you are using there.

**Comment by fredthedoggy** [comment]
I was using %vault_prefix% & %Essentials_Nick%, and turns out those placeholders are parsed for all players on the team separately, not for the sender.

Also Unrelated, could Listener Priority be added to the config? My Chat Plugin's lowest Listener still overrides This.

**Comment by tastybento** [comment]
Okay, so as I understand this, it is not a bug.

For the Listener Priority - it's been in the config since the previous release, so you should be able to set it.
