### ISSUE TITLE
Downgrade priority or implement config option for changing eventPriorities

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Chat#24]
#### Is your feature request related to a problem?
Yes, it is. There are conflicts with events. [ChatControl](https://www.spigotmc.org/resources/chatcontrol%E2%84%A2-the-ultimate-chat-plugin-500-000-downloads-1-2-5-1-16-4.271/) is blocking unwanted messages on our server, but doesn't get to cancel the ones that are processed in team chats or so. Specifically speaking of EventPriority in ChatListener, onChat method.

#### Describe the solution you'd like us to implement.
I am aware that ChatControl posseses ability to change the eventPriority in configuration, and so we tried, but then it breaks with EssentialsChat and lots of other plugins. It was such a mess to be fixed. We kept recompiling Chat's addon source code for months - placing it to .LOW, but it's kinda getting annoying. I would kindly ask for a config option to change the EventPriority or just downgrade it to EventPriority.LOW, because Chat addon shouldn't really check messages in parallel with other plugins that are so by default on .NORMAL. 

#### Describe solutions you've considered.
- Downgrade priority to .LOW
- Implement config option for it to be handled manually by users

### Additional context
- None for now

**Comment by tastybento** [comment]
If you make changes to code and think it would be something you'd like in the upstream then just submit a PR and make it easy for me. :-) Anyway, I made the change. If it works for you then close.

**Comment by wellnesscookie** [comment]
There's a PR, please take a look when you can.

**Comment by tastybento** [comment]
Thanks!
