### ISSUE TITLE
fast chat team

### ISSUE THREAD

**Issue by Bricec6** [BentoBoxWorld/Chat#4]
ello, I'm here to make a suggestion that would be the addition of orders
Player:
/tc <message> - Sends the message directly to the teamchat without the need ON for teamchat

Alias /tc: /ischat

Sorry, I translate with a translator.

Thank you. Thank you.

**Comment by DuckSoft** [comment]
I think you should address this problem using an alias plugin.
https://www.curseforge.com/minecraft/bukkit-plugins/command-alias

Plugins may risk clashing shortcut alias commands, so it's better to manage them by users, not by plugins themselves.

That's what I've thought.

**Comment by wellnesscookie** [comment]
This is implemented with the latest development build, and the commands for direct sending without need of toggling are:
/is tc [message]
/is chat [message]

Or to only toggle:
/is tc
/is chat

Tho what is not yet implemented is the alias you were looking, only "tc" (without is) and so.

**Comment by tastybento** [comment]
Agreed on using other plugins to alias. We'll close this now.
